---

env: local

listen:
    type: tcp
    read_timeout: 10s
    write_timeout: 10s
    shutdown_timeout: 15s

postgresql:
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: 30m
    conn_max_idle_time: 2m
    connect_timeout: 15s
    query_timeout: 5s
    migrations_path: ./migrations